# -*- coding: utf-8 -*-
"""tp0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AK8Khm69IJAaFuO8h50eFUUgu4TJUEs7
"""

import seaborn.objects as so
from gapminder import gapminder



def plot():
    figura = (
        (so.Plot(data = gapminder[gapminder.continent == "Americas"], x = "year", y = "lifeExp" )
          .add(so.Line (linewidth = 2), color = "country")
          .label(title = "Expectativa de vida en países de America", x = "Año", y = "Expectativa de vida", color = "Países")

        )
    )
    return dict(
        descripcion="Expectativa de vida en países de America",
        autor="Gonzalez Gabriel Ezequiel",
        figura=figura,
    )

